### PR TITLE
Remove Makefile from source

### PR DESCRIPTION
**Pull request by zgrimshell**
Makefile is not needed and it has sudo calls in it which makes a security risk (as well as it can make system risk while pulling libraries which aren't compatible with current system packages) and ask for password during building of Debian packages (package building shoudn't request password).

### CODE REVIEW

**Comment by ids1024** [comment]
Merged into develop branch.

**Comment by ids1024** [comment]
@zgrimshell Probably going to release pafy tomorrow (California time) once one small thing is fixed. I think the debian directory should probably be updated before the release is tagged.

An mpsyt release may follow not long after. There is one known bug that needs to be fixed first, but just that if nothing else comes up the the mean time.

**Comment by zgrimshell** [comment]
I'll try to catch it up tomorrow and prepare the debian directory for it. (will get up on channel on coordinate with you). There are no major changes regarding debian part (AFAIK) only to prepare builds for python2 and python3 (removal of makefile made main obstacle gone)

**Comment by ids1024** [comment]
@zgrimshell May not be released today. The unittests are still failing although I fixed the problem I was seeing earlier. The failures are also inconsistent, which is annoying but also suggests a legitimate issue that needs to be dealt with.

**Comment by zgrimshell** [comment]
I agree. I'll maybe have time tonight (CET) to hop on channels and help with debugging (if someone doesn't solve before that which would be great).

**Pull request closed without merging**
